### ISSUE TITLE
Vertical Overdraw: End of text

### ISSUE THREAD

**Issue by vinaychandra** [embedded-graphics/embedded-text#66]
When implementing a "console" like scenario using this, it would be simpler if we have an option to show the last characters rather than the first few when drawing.
For example, if the string is "1 2 3 4 5 ..... 100", today it would produce "1 2 3 4 .. 50" if the space is not enough. We might also want to show "51 52 53... 100" as on option so that we can keep on having a `tail` like command.

As an alternative, it would suffice that the struct return a "number of characters that would fit in the view" so that the user can remove the prefix (1 2 .. 50 in above example) as needed.

**Comment by bugadani** [comment]
This is a good idea indeed! Technically, you should be able to implement it without modifying e-t, but since the crate is stuck in a limbo between a rich textbox and a half-baked terminal emulator, it's a feature that has it's place.

There's a bit of complication with regards to different vertical alignments, that may be somewhat non-trivial. For example, what behaviour would you expect from this mode, when the text is vertically centered?

**Comment by vinaychandra** [comment]
Yes, there are some unknows as you mention. The ideal take would be like an `overflow: scroll` with the scrollbar removed. Implementation could unfortunately be quite complicated though.
For the initial release, it can be forced that the align is left only.

**Comment by bugadani** [comment]
@vinaychandra does this looks something like you want?

![image](https://user-images.githubusercontent.com/977627/99066854-f381c180-25a9-11eb-94af-cc1a767a39aa.png)

**Comment by vinaychandra** [comment]
That looks exactly as i expected. Thanks!

**Comment by bugadani** [comment]
Then it shall arrive with the next release :) Thanks for the idea!

**Comment by bugadani** [comment]
Just a heads-up that this feature will be changed in the future. Instead of an alignment option, you'll need to use the `Tail` plugin. I'm hoping the new solution will be a bit more flexible (i.e. it would even work with vertically centered text).
